# Generated by Django 5.2.7 on 2025-10-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('hora_asignacion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('prestado', 'prestado'), ('disponible', 'disponible')], default='disponible', max_length=10)),
                ('nivel_estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.estantenivel')),
                ('tomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.tomo')),
            ],
        ),
    ]
