# Generated by Django 5.2.7 on 2025-10-02 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo_almacen', models.CharField(choices=[('material', 'Material'), ('archivos', 'Archivos')], max_length=8, validators=[django.core.validators.RegexValidator(message='Tipo de almacen no válido.', regex='^(material|archivos)$')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nivel', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_estante', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
            },
        ),
        migrations.CreateModel(
            name='EstanteNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('hay espacio', 'hay espacio'), ('ocupado', 'ocupado')], max_length=11, validators=[django.core.validators.RegexValidator(message='Estado de nivel de estante inválido', regex='^(hay espacio|ocupado)$')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.estante')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.nivel')),
            ],
            options={
                'verbose_name': 'Nivel de Estante',
                'verbose_name_plural': 'Niveles de Estante',
                'constraints': [models.UniqueConstraint(fields=('estante', 'nivel'), name='unique_estante_nivel')],
            },
        ),
    ]
