# Generated by Django 5.2.7 on 2025-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estante',
            constraint=models.UniqueConstraint(fields=('nro_estante', 'almacen'), name='unique_estante_almacen'),
        ),
    ]
