# Generated by Django 5.2.6 on 2025-10-01 14:47

import apis.archivos.functions.guardar_archivo
import apis.archivos.functions.validar_pdf
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_tomo', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=25)),
                ('glosa', models.TextField()),
                ('nro_fojas_total', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_apertura', models.DateField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], max_length=7, validators=[django.core.validators.RegexValidator(message='Estado de Tomo inválido.', regex='^(abierto|cerrado)$')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tomo',
                'verbose_name_plural': 'Tomos',
                'constraints': [models.UniqueConstraint(fields=('nro_tomo', 'fecha_apertura'), name='unique_tomo_fecha_apertura')],
            },
        ),
        migrations.CreateModel(
            name='DetalleTomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_archivo', models.PositiveSmallIntegerField()),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apis.archivos.functions.guardar_archivo.get_upload_to, validators=[apis.archivos.functions.validar_pdf.validar_pdf])),
                ('nro_fojas', models.PositiveSmallIntegerField(default=1)),
                ('fecha_adjunto', models.DateField(blank=True, null=True)),
                ('estado_archivo', models.CharField(choices=[('adjunto', 'adjunto'), ('no adjunto', 'no adjunto')], default='no adjunto', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.tomo')),
            ],
            options={
                'verbose_name': 'Detalle Tomo',
                'verbose_name_plural': 'Detalles de Tomo',
                'constraints': [models.UniqueConstraint(fields=('nro_archivo', 'tomo'), name='unique_archivo_tomo')],
            },
        ),
    ]
