# Generated by Django 5.2.7 on 2025-10-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=65, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('nro_item', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.unidad')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('ci', models.CharField(max_length=7)),
                ('alta', models.DateField(auto_now_add=True)),
                ('baja', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.puesto')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'apellido_paterno', 'apellido_materno'), name='unique_full_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.UniqueConstraint(fields=('departamento', 'unidad'), name='unique_departamento_unidad'),
        ),
    ]
